export enum ItemType {
  ANCIENT = 'ANCIENT',
  VINTAGE = 'VINTAGE',
  CHROMA = 'CHROMA',
  GODLY = 'GODLY',
  LEGENDARY = 'LEGENDARY',
  RARE = 'RARE',
  UNCOMMON = 'UNCOMMON',
  COMMON = 'COMMON',
  PET = 'PET',
  MISC = 'MISC',
  UNIQUE = 'UNIQUE',
}

export enum ItemCategory {
  SEASON1 = 'SEASON1',
  CLASSIC = 'CLASSIC',
  HOLIDAY_CHRISTMAS = 'HOLIDAY_CHRISTMAS',
  HOLIDAY_HALLOWEEN = 'HOLIDAY_HALLOWEEN',
}

export enum ItemStability {
  RISING = 'RISING',
  OVERPAID_FOR = 'OVERPAID_FOR',
  DOING_WELL = 'DOING_WELL',
  IMPROVING = 'IMPROVING',
  FLUCTUATING = 'FLUCTUATING',
  RECEDING = 'RECEDING',
  STABLE = 'STABLE',
  UNDERPAID_FOR = 'UNDERPAID_FOR',
  DECREASING = 'DECREASING',
  UNSAFE = 'UNSAFE',
}

export enum ItemSource {
  SUPREME = 'SUPREME',
  MM2VALUES = 'MM2VALUES',
}
